apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coin-filp-work-flow
spec:
  project: default
  source:
    repoURL: https://github.com/PaboO25/argo.git
    targetRevision: HEAD
    path: argo-work-flow
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd